"""Add Basic Support

Revision ID: 4285618d77
Revises: 
Create Date: 2015-10-14 20:09:32.749294

"""

# revision identifiers, used by Alembic.
revision = '4285618d77'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cid', sa.Integer(), nullable=True),
    sa.Column('created', sa.Integer(), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('authorId', sa.Integer(), nullable=True),
    sa.Column('ownerId', sa.Integer(), nullable=True),
    sa.Column('mail', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('agent', sa.String(length=200), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('parent', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_cid'), 'comments', ['cid'], unique=False)
    op.create_table('contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('slug', sa.String(length=200), nullable=True),
    sa.Column('created', sa.Integer(), nullable=True),
    sa.Column('modified', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('authorId', sa.Integer(), nullable=True),
    sa.Column('template', sa.String(length=32), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('password', sa.String(length=32), nullable=True),
    sa.Column('commentsNum', sa.Integer(), nullable=True),
    sa.Column('allowComment', sa.CHAR(length=1), nullable=True),
    sa.Column('allowPing', sa.CHAR(length=1), nullable=True),
    sa.Column('allowFeed', sa.CHAR(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contents_created'), 'contents', ['created'], unique=False)
    op.create_index(op.f('ix_contents_slug'), 'contents', ['slug'], unique=False)
    op.create_table('metas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('slug', sa.String(length=200), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metas_slug'), 'metas', ['slug'], unique=False)
    op.create_table('options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'name', 'user')
    )
    op.create_table('relationships',
    sa.Column('cid', sa.Integer(), nullable=False),
    sa.Column('mid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('cid', 'mid')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('password', sa.String(length=32), nullable=True),
    sa.Column('mail', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('screenName', sa.String(length=32), nullable=True),
    sa.Column('created', sa.Integer(), nullable=True),
    sa.Column('activated', sa.Integer(), nullable=True),
    sa.Column('logged', sa.Integer(), nullable=True),
    sa.Column('group', sa.String(length=16), nullable=True),
    sa.Column('authCode', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mail'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('relationships')
    op.drop_table('options')
    op.drop_index(op.f('ix_metas_slug'), table_name='metas')
    op.drop_table('metas')
    op.drop_index(op.f('ix_contents_slug'), table_name='contents')
    op.drop_index(op.f('ix_contents_created'), table_name='contents')
    op.drop_table('contents')
    op.drop_index(op.f('ix_comments_cid'), table_name='comments')
    op.drop_table('comments')
    ### end Alembic commands ###
